import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import AdviceGenerator from '../components/adviceGeneretor/adviceGenerator';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Advice Generator</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/images/favicon.png' />
      </Head>
      <main className={styles.container}>
        <AdviceGenerator />
      </main>
    </>
  );
};

export default Home;
